### ISSUE TITLE
Watch Error: FSEventStreamFlushSync(): failed assertion

### ISSUE THREAD

**Issue by tbremer** [gruntjs/grunt-contrib-watch#415]
I am getting the following error after `Running "watch" task` restarts

```
2015-03-02 11:19 grunt[7732] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```

Happens with these versions:
```
$ node 0.11.6 - 0.12.0
$ npm 2.5.1
```

**Comment by crimann** [comment]
Get exactly the same message when watch restarts. Happens on several projects with different configurations and on two different Macs.

Tested with those npm versions:

'''
$ node v0.12.0
$ npm 2.3.0, 2.5.0, 2.7.0, 2.7.1
'''

**Comment by tannerlinsley** [comment]
This happens for me too

**Comment by TheBox193** [comment]
+1 Ditto

**Comment by lancepadgett** [comment]
Same here. Can't seem to find a solution...

**Comment by alphanull** [comment]
+1 Yeah, same here. Watch task seems to actually work, but nonetheless the message is a bit annoying. I am on Yosemite 10.10.2

**Comment by greenchapter** [comment]
Same here, whats the problem?

**Comment by infinityplusone** [comment]
Same problem. Upgraded to node.js v0.12.1, and it is still there.

**Comment by ThomasHoadley** [comment]
Same problem.

**Comment by greenchapter** [comment]
Does anyone write an bugreport to the nodejs guys?

**Comment by vemec** [comment]
Same here

```bash
$ node v0.12.2
$ npm 2.7.4
OSX 10.10.2 (14C1514)
```
```bash
grunt[22532] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```

**Comment by vladikoff** [comment]
If anyone wants to try this in io.js, should be fixed there.

**Comment by of6** [comment]
Still happening for me as well

node v0.12.2
npm 2.7.5
grunt-contrib-watch 0.6.1
OS X 10.10.3

This seems to happen more when it has to run an uglify or concat task. But both are at the latest version.

**Comment by awenro** [comment]
Same here on

node v0.12.0
npm 2.5.1
grunt-contrib-watch 0.6.1
OS X 10.9.5

Happens only if I set the option `spawn: false`. The tasks don't run correctly, it's not just the message for me.

**Comment by SudoCat** [comment]
Same problem - Seems to be functioning fine, but always gives this error.

```
Node: v0.12.2,
NPM: 2.7.5,
grunt: ^0.4.5,
grunt-contrib-concat: ^0.5.1,
grunt-contrib-imagemin: ^0.9.4,
grunt-contrib-uglify: ^0.9.1,
grunt-contrib-watch: ^0.6.1,
grunt-sass: ^0.18.1
OS X 10.10.2
```
```
(FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```

**Comment by JWGmeligMeyling** [comment]
Can confirm.

**Comment by yumyo** [comment]
same here
````
Node v0.12.2
grunt-cli v0.1.13
grunt v0.4.5
grunt-contrib-watch 0.6.1
OS X 10.10.3
````

**Comment by paulhayes** [comment]
I'm also experiencing this issue

```
Node v0.12.2
Npm v2.7.5
Packages:
├── grunt@0.4.5
├── grunt-contrib-connect@0.10.1
├── grunt-contrib-copy@0.8.0
├── grunt-contrib-less@1.0.1
├── grunt-contrib-uglify@0.9.1
├── grunt-contrib-watch@0.6.1
├── grunt-exec@0.4.6
└── grunt-express-server@0.5.1
```

**Comment by digitalcraftco** [comment]
Same here.
node: v0.12.0

Removing spawn from Watch > Scripts > Options:{ } stops the error. What is spawn anyway again?

**Comment by mikehdt** [comment]
Might this potentially be why?
https://github.com/bdkjones/fseventsbug/wiki/realpath()-And-FSEvents

**Comment by juanbrujo** [comment]
@digitalcraftco solution worked with v0.12.7, removing all spawns from watch: {} task (even if they're false)

**Comment by digitalcraftco** [comment]
@juanbrujo Thanks for the follow up. Indeed this has fixed the issue for newer versions.

**Comment by Fishrock123** [comment]
Interesting. Is 0.11.6 the earliest node version this manifests in? We've had the above linked io.js issue for this for a while but haven't really been able to debug it.

**Comment by flekschas** [comment]
@digitalcraftco It defines whether a new task should be spawned or not. See https://github.com/gruntjs/grunt-contrib-watch#optionsspawn

Removing `spawn` from options does avoid but not fix the issue.

**Comment by tconroy** [comment]
+1 getting this as well still.

**Comment by teejayhh** [comment]
Interesting to note, as soon as you remove the spawn = false property the compile time jumps up dramatically, in my case from 0.3sec to 4.3sec !!

**Comment by jlujan** [comment]
I see similar messages in a C app using libuv and uv_fs_event* I wrote as well. Linked to https://github.com/nodejs/node/issues/854 which mentions this issue.

**Comment by maruf89** [comment]
Absolutely nothing changed in my dependencies for the last month at least and I randomly just started seeing this

**Comment by Fishrock123** [comment]
@maruf89 Did you change OS X versions?

**Comment by maruf89** [comment]
No, I'm still on Yosemite 10.10.3 - The only thing that changed is I got a hard drive cable replaced but no software/npm deps changed

**Comment by AlexChesters** [comment]
Never had this problem on Yosemite, upgraded to El Capitan and now it happens...

**Comment by ogmios2** [comment]
+1 having same issue

**Comment by tuffz** [comment]
@maruf89, same by me, i had only changed the hard drive cable.

**Comment by cb1kenobi** [comment]
This is still an issue with Node.js 4.4.7 and 6.3.1. I'm on OS X 10.11.6. I'm NOT using chokidar, fsevents, gaze, or any other filesystem watching library. I'm only using the built-in `fs.watch()`.

**Comment by Pedder** [comment]
+1

**Comment by ourcore** [comment]
What are the side-effects to this error? It started occurring in my project after I added imagemin

**Comment by Fishrock123** [comment]
> What are the side-effects to this error?

Unknown, probably nothing impactful? I think the OS just retries or something.

---

Strange that multiple people would see it after a harddrive cable, maybe it's an odd apple hardware issue?

**Comment by alphanull** [comment]
Am sure it has nothing to do with hardware. As Fishrock123 said, no apparent(!) sideeffects, but still annoying. So a fix definetly would be nice, since also a lot of systems seem to be affected.

**Comment by ekkis** [comment]
I'm having this issue with node v7.3.0 on OSX 10.11.6 (El Capitan) and grunt v0.4.5, grunt-cli v1.2.0

**Comment by cwklausing** [comment]
I can't make sense of why this worked, but I was having the exact same issue, and adding more specific selectors for the files I was watching resolved the issue. Here's a sample of my old Gruntfile:
```		
watch: {
	css: {
		files: '**/*.scss',
		tasks: ['sass']
	},
	js: {
		files: '**/*.js',
		tasks: ['rollup']
	}
}
```
and here's my new Gruntfile
```		
watch: {
	css: {
		files: './assets/**/*.scss',
		tasks: ['sass']
	},
	js: {
		files: './assets/**/*.js',
		tasks: ['rollup']
	}
}
```

What's more--my old grunt process was using a huge chunk of my CPU, and with my more specific file selection, I use only 2-3%.
